version: '3.6'

services:
  frontend:
    restart: unless-stopped
    container_name: frontend-chernobyl
    build: ./
    command: yarn start
    env_file:
      - .env
    expose:
      - 3000
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
    name: nginx-proxy
